"""Live bet365 bet-boost scraper.

Why this exists: the bet-boost content is delivered over bet365's websocket push
feed using fresh, per-request `x-net-sync-term` tokens generated by client-side
JavaScript, so captured HTTP requests can't be replayed (you get an empty 200).
Rather than fight that, we drive a real browser to the boosts page and scrape the
fully rendered DOM -- exactly what a human sees -- which is robust to all the
token/transport churn underneath.

Usage:
    python boost_scraper.py

An Edge window opens using a persistent profile in ./.pw-profile, so you log in
to bet365 once and the session is reused on later runs. Navigate to the World Cup
Bet Boost tab so the cards are visible, then press ENTER to snapshot. The script
parses the rendered boosts into structured data and writes boosts.json:

    [{"match": "...", "kickoff": "...",
      "boosts": [{"title", "legs", "was", "now", ...}]}]

capture_debug.json / page_dump.html are written too, for diagnostics.
"""

import json
import os
import re
import sys

from dotenv import load_dotenv
from playwright.sync_api import sync_playwright

from inplaydiaryapi import InPlays

# A boost card ends with two stacked odds (old then boosted), e.g. 5.50 / 6.00.
ODDS_RE = re.compile(r"^\d+\.\d+$")
# Match headers are immediately followed by a kickoff line like "Thu 25 Jun 17:00".
KICKOFF_RE = re.compile(
    r"^(Mon|Tue|Wed|Thu|Fri|Sat|Sun)\s+\d{1,2}\s+\w{3,}\s+\d{1,2}:\d{2}$")

load_dotenv()

# Persistent browser profile -> log in once, reuse the session afterwards.
PROFILE_DIR = os.path.join(os.path.dirname(__file__), ".pw-profile")
START_URL = "https://www.bet365.com.au/"
OUTPUT_FILE = os.path.join(os.path.dirname(__file__), "boosts.json")

# bet365 login credentials, read from .env (fill these in yourself).
# .strip() guards against trailing whitespace/newlines pasted into .env.
BET365_USERNAME = (os.getenv("BET365_USERNAME") or "").strip()
BET365_PASSWORD = (os.getenv("BET365_PASSWORD") or "").strip()

# Only capture the actual bet-boost content feeds. We match "betboost" in the
# URL *path* -- NOT the broad "contentapi", which also matches the homepage
# routing manifest (websiteroutingdatacontentapi) and pollutes the output.
CAPTURE_SUBSTRINGS = ("betboost",)


def is_logged_in(page):
    """Heuristic: the 'Log In' control is only present when logged out."""
    try:
        return page.locator(".hm-MainHeaderRHSLoggedOutWide_Login").count() == 0
    except Exception:
        return False


def login(page):
    """Log in using BET365_USERNAME / BET365_PASSWORD from .env.

    No-op if creds aren't set or we're already logged in (persistent profile).
    bet365's markup changes often, so selectors are best-effort with fallbacks;
    if login silently fails, just log in by hand once and the profile sticks.
    """
    if is_logged_in(page):
        print("Already logged in (reused profile session).")
        return
    if not (BET365_USERNAME and BET365_PASSWORD):
        print("BET365_USERNAME / BET365_PASSWORD not set in .env -- "
              "log in manually in the browser window.")
        return

    # Print lengths only (never the secrets) so you can confirm .env parsed
    # the full values -- a short password usually means a '#' truncated it.
    print(f"Attempting auto-login with .env credentials "
          f"(username {len(BET365_USERNAME)} chars, "
          f"password {len(BET365_PASSWORD)} chars)...")
    try:
        # Open the login overlay.
        page.locator(".hm-MainHeaderRHSLoggedOutWide_Login").first.click(timeout=15000)

        # Username/password fields. Try the stable class names first, then
        # fall back to placeholder text.
        user = page.locator(
            ".lms-StandardLogin_Username, input[placeholder='Username']"
        ).first
        pwd = page.locator(
            ".lms-StandardLogin_Password, input[placeholder='Password']"
        ).first

        # Type like a real user: focus, clear, then key-by-key so bet365's
        # field validation fires the same events it does for manual input.
        # (A plain .fill() pastes the value and some sites reject it.)
        user.click(timeout=15000)
        user.fill("")
        user.type(BET365_USERNAME, delay=40)
        pwd.click(timeout=15000)
        pwd.fill("")
        pwd.type(BET365_PASSWORD, delay=40)

        # Submit.
        page.locator(
            ".lms-LoginButton, .lms-StandardLogin_LoginButton, "
            "button:has-text('Log In')"
        ).first.click(timeout=15000)

        page.wait_for_timeout(4000)
        if is_logged_in(page):
            print("Login successful.")
        else:
            print("Login may have failed (still see the Log In control). "
                  "Finish logging in manually if needed.")
    except Exception as e:
        print(f"Auto-login error: {e}\nLog in manually in the browser window.")


def main():
    captured = []      # list of {url, status, body} -- ALL text HTTP responses
    ws_frames = []     # list of {url, dir, data} -- websocket frames
    page_texts = []    # rendered body innerText from each snapshot

    with sync_playwright() as p:
        context = p.chromium.launch_persistent_context(
            PROFILE_DIR,
            headless=False,
            # Use the locally installed Microsoft Edge instead of Playwright's
            # bundled Chromium. Edge is Chromium-based, so the same API works.
            channel="msedge",
            # By default Playwright locks the page to a fixed viewport that
            # doesn't follow the OS window, so manually resizing the window
            # doesn't reflow the content. no_viewport=True makes the page track
            # the real window size like a normal browser.
            no_viewport=True,
            args=["--disable-blink-features=AutomationControlled"],
        )
        page = context.pages[0] if context.pages else context.new_page()

        # --- DIAGNOSTIC MODE -------------------------------------------------
        # We don't yet know which channel carries the World Cup boost data, so
        # capture EVERYTHING (every text HTTP response + every websocket frame)
        # and dump it to capture_debug.json. Once we can see the real boost
        # feed there, we'll narrow back down to just that.
        def on_response(response):
            url = response.url
            try:
                body = response.text()
            except Exception:
                return
            if not body:
                return
            ct = (response.headers or {}).get("content-type", "")
            captured.append({
                "url": url, "status": response.status,
                "content_type": ct, "body": body,
            })
            # Print a compact line for anything that looks like content data.
            if "contentapi" in url or "betboost" in url.lower():
                print(f"  [http] {response.status} {len(body):>6}B  "
                      f"{ct[:20]:<20} {url[:80]}")

        def on_websocket(ws):
            print(f"  [ws OPEN] {ws.url[:90]}")
            ws.on("framereceived", lambda payload: ws_frames.append(
                {"url": ws.url, "dir": "recv", "data": _frame_text(payload)}))
            ws.on("framesent", lambda payload: ws_frames.append(
                {"url": ws.url, "dir": "sent", "data": _frame_text(payload)}))

        page.on("response", on_response)
        page.on("websocket", on_websocket)
        # store for process()/debug dump
        main._ws_frames = ws_frames

        print(f"Opening {START_URL} ...")
        page.goto(START_URL, wait_until="domcontentloaded")

        login(page)

        print("\n" + "=" * 70)
        print("In the AUTOMATION BROWSER WINDOW (not your normal browser):")
        print("  1. Go to SOCCER -> World Cup, and open its BET BOOSTS so you")
        print("     can SEE the soccer boost cards (Bosnia v Qatar etc).")
        print("  2. Press ENTER here to snapshot what's currently subscribed.")
        print("  3. If you only see racing topics, navigate again and snapshot")
        print("     again -- captures accumulate. Type 'q' then ENTER to finish.")
        print("=" * 70)
        while True:
            try:
                cmd = input("\n[ENTER]=snapshot (dump page + topics)   'q'=finish & save: ").strip().lower()
            except (EOFError, KeyboardInterrupt):
                break
            if cmd == "q":
                break
            dump_page(page, page_texts)  # grab + parse the rendered boosts DOM

        context.close()

    dump_debug(captured, ws_frames)
    process(page_texts)


def _frame_text(payload):
    """Websocket frames may arrive as str or bytes; normalise to str."""
    if isinstance(payload, bytes):
        return payload.decode("utf-8", "replace")
    return payload


# bet365's push feed (Diffusion-style). A single websocket frame may bundle
# several messages separated by \x08; each is <TYPEBYTE><TOPIC>\x01<payload>,
# and <payload> is the same pipe/semicolon format InPlays.parse() handles.
WS_MSG_SEP = "\x08"
WS_TOPIC_SEP = "\x01"
WS_TYPE_TOPIC_LOAD = "\x14"   # full topic snapshot
WS_TYPE_DELTA = "\x15"        # incremental update


def parse_ws_frame(data):
    """Decode one captured websocket frame into a list of (topic, records).

    Only topic-load / delta frames carry content; handshake/ping/subscribe
    frames are skipped. Records reuse InPlays.parse on the topic payload.
    """
    out = []
    for msg in data.split(WS_MSG_SEP):
        if not msg:
            continue
        type_byte = msg[0]
        if type_byte not in (WS_TYPE_TOPIC_LOAD, WS_TYPE_DELTA):
            continue  # control frame, not content
        body = msg[1:]
        if WS_TOPIC_SEP not in body:
            continue
        topic, payload = body.split(WS_TOPIC_SEP, 1)
        payload = payload.rstrip("\x00")
        records = InPlays.parse(payload) if payload else []
        out.append((topic, records))
    return out


def dump_debug(captured, ws_frames):
    """Write everything we saw so we can identify the boost channel.

    capture_debug.json contains every text HTTP response (url + body) and every
    websocket frame. Share the URL list / relevant bodies and we narrow the
    capture filter to the real boost feed.
    """
    debug = {
        "http": [
            {"url": c["url"], "status": c["status"],
             "content_type": c.get("content_type", ""),
             "bytes": len(c["body"]),
             "body_preview": c["body"][:400]}
            for c in captured
        ],
        "websockets": [
            {"url": f["url"], "dir": f["dir"], "bytes": len(f["data"]),
             "data_preview": f["data"][:400]}
            for f in ws_frames
        ],
    }
    path = os.path.join(os.path.dirname(__file__), "capture_debug.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(debug, fh, indent=2, ensure_ascii=False)

    print(f"\n--- DIAGNOSTIC SUMMARY ---")
    print(f"HTTP responses captured: {len(captured)}")
    print(f"Websocket frames captured: {len(ws_frames)}")
    # Show content-API URLs -- the boost feed is almost certainly among these.
    content_urls = sorted({c["url"].split("?")[0]
                           for c in captured if "contentapi" in c["url"]})
    print("\nDistinct *contentapi* endpoints hit:")
    for u in content_urls:
        print(f"  {u}")
    ws_urls = sorted({f["url"] for f in ws_frames})
    if ws_urls:
        print("\nWebsocket connections seen:")
        for u in ws_urls:
            print(f"  {u}")
    print(f"\nFull detail written to capture_debug.json")
    print("--- END DIAGNOSTIC ---\n")


def dump_page(page, page_texts):
    """Snapshot the rendered boosts: parse them now and stash the raw text.

    Writes page_dump.html / boosts_text.txt for diagnostics, appends the body
    innerText to page_texts (process() parses the latest), and prints a live
    count so you can confirm the soccer boosts are actually on screen.
    """
    html_path = os.path.join(os.path.dirname(__file__), "page_dump.html")
    text_path = os.path.join(os.path.dirname(__file__), "boosts_text.txt")
    try:
        html = page.content()
        with open(html_path, "w", encoding="utf-8") as fh:
            fh.write(html)
        # innerText of the body collapses to what's actually visible on screen.
        text = page.evaluate("() => document.body.innerText")
        with open(text_path, "w", encoding="utf-8") as fh:
            fh.write(text)
        page_texts.append(text)

        matches = parse_boosts_text(text)
        n_boosts = sum(len(m["boosts"]) for m in matches)
        print(f"  [dom] snapshot: {len(matches)} matches / {n_boosts} boosts "
              f"on screen.")
        for m in matches[:8]:
            print(f"        - {m['match']} ({len(m['boosts'])} boosts)")
        if len(matches) > 8:
            print(f"        ... and {len(matches) - 8} more")
        if not matches:
            print("        (no boosts parsed -- are the Bet Boost cards visible?)")
    except Exception as e:
        print(f"  [dom] dump failed: {e}")


def parse_boosts_text(text):
    """Parse the rendered boosts page innerText into structured boosts.

    Structure on screen, per match:
        <match name>
        <kickoff>                     e.g. "Thu 25 Jun 17:00"
        <boost title>                 e.g. "Edin Dzeko" or "Dragons To Destroy"
        <leg line>...                 0+ selection lines (single-leg boosts have
                                      their market here, e.g. "Score with a Header")
        <was odds>  <now odds>        two stacked decimals close the boost
    Returns: [{"match", "kickoff", "boosts": [{"title","legs","was","now",
              "more_legs_hidden"}]}].
    """
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    matches = []
    current = None
    buffer = []
    i = 0
    while i < len(lines):
        line = lines[i]
        # A match header is any line immediately followed by a kickoff line.
        if i + 1 < len(lines) and KICKOFF_RE.match(lines[i + 1]):
            current = {"match": line, "kickoff": lines[i + 1], "boosts": []}
            matches.append(current)
            buffer = []
            i += 2
            continue
        # A boost closes with two stacked odds: original then boosted.
        if (current and ODDS_RE.match(line)
                and i + 1 < len(lines) and ODDS_RE.match(lines[i + 1])):
            title = buffer[0] if buffer else ""
            legs = [b for b in buffer[1:] if not b.lower().startswith("view ")]
            hidden = any(b.lower().startswith("view ") for b in buffer[1:])
            current["boosts"].append({
                "title": title,
                "legs": legs,
                "more_legs_hidden": hidden,
                "was": float(line),
                "now": float(lines[i + 1]),
            })
            buffer = []
            i += 2
            continue
        if current is not None:
            buffer.append(line)
        i += 1
    return matches


def decode_topics(ws_frames):
    """Merge all received websocket frames into {topic: [records]}."""
    topics = {}
    for f in ws_frames:
        if f["dir"] != "recv":
            continue
        for topic, records in parse_ws_frame(f["data"]):
            topics.setdefault(topic, []).extend(records)
    return topics


def summarize_topics(ws_frames):
    """Print the current topic list so the soccer feed is easy to spot."""
    topics = decode_topics(ws_frames)
    if not topics:
        print("  (no decodable topics yet -- navigate to the boosts and wait "
              "for the cards to render)")
        return
    print("\n--- WEBSOCKET TOPICS DECODED (live snapshot) ---")
    for topic in sorted(topics, key=lambda t: -len(topics[t])):
        recs = topics[topic]
        names = [r["NA"] for r in recs if r.get("NA")][:3]
        hint = ("  e.g. " + ", ".join(names)) if names else ""
        print(f"  {len(recs):>4} rec  {topic[:45]:<45}{hint}")
    print("--- END TOPICS ---")


def process(page_texts):
    """Parse the captured boost page(s) and write structured boosts.json."""
    if not page_texts:
        print("\nNo page snapshot captured. Open the World Cup Bet Boost tab so "
              "the cards are visible, press ENTER to snapshot, then 'q'.")
        return

    # Use the snapshot that yielded the most boosts (in case you snapshotted a
    # non-boost page at some point too).
    best = max((parse_boosts_text(t) for t in page_texts),
               key=lambda ms: sum(len(m["boosts"]) for m in ms))

    total = sum(len(m["boosts"]) for m in best)
    if not total:
        print("\nNo boosts parsed from the snapshot(s). Make sure the Bet Boost "
              "cards were on screen before pressing ENTER.")
        return

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(best, f, indent=2, ensure_ascii=False)
    print(f"\nWrote {len(best)} matches / {total} boosts to {OUTPUT_FILE}")
    print("\nSample:")
    for m in best[:3]:
        print(f"  {m['match']} ({m['kickoff']}):")
        for b in m["boosts"][:3]:
            print(f"    {b['was']} -> {b['now']}  {b['title']}")


if __name__ == "__main__":
    main()
